language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- pypy

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
  - python: pypy
cache: python
install: pip install tox
script: tox -e py
